# Generated by Django 3.1.3 on 2020-11-18 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magicjourney', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='level',
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('blood', models.CharField(blank=True, choices=[('muggle', 'Muggle'), ('half-blood', 'Half-blood'), ('pure-blood', 'Pure-blood')], max_length=30)),
                ('hp', models.IntegerField(default=0)),
                ('defence', models.IntegerField(default=0)),
                ('charms', models.IntegerField(default=0)),
                ('transmutation', models.IntegerField(default=0)),
                ('potions', models.IntegerField(default=0)),
                ('charisma', models.IntegerField(default=0)),
                ('money', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
