# Generated by Django 3.1.3 on 2020-11-19 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magicjourney', '0002_auto_20201118_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='transmutation',
            new_name='transfiguration',
        ),
    ]
