# Generated by Django 3.1.3 on 2020-11-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicjourney', '0003_auto_20201119_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='house',
            field=models.CharField(blank=True, choices=[('Gryffindor', 'Gryffindor'), ('Ravenclaw', 'Ravenclaw'), ('Hufflepuff', 'Hufflepuff'), ('Slytherin', 'Slytherin')], max_length=30),
        ),
    ]
