# Generated by Django 3.1.3 on 2020-11-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicjourney', '0005_auto_20201120_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='skills_points',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='player',
            name='xp',
            field=models.IntegerField(default=100),
        ),
    ]
