# Generated by Django 3.1.3 on 2020-11-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicjourney', '0006_auto_20201120_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='story_status',
            field=models.IntegerField(default=0),
        ),
    ]
