# Generated by Django 3.1.3 on 2020-11-20 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magicjourney', '0008_auto_20201120_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('required_skill', models.CharField(max_length=20)),
                ('required_value', models.IntegerField(default=0)),
                ('effects_skill', models.CharField(max_length=20)),
                ('effects_value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cloak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('hp', models.IntegerField(default=0)),
                ('defence', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Wand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(default=10)),
                ('flexibility', models.CharField(max_length=30)),
                ('core', models.CharField(max_length=40)),
                ('wood', models.CharField(max_length=30)),
                ('defence', models.IntegerField(default=0)),
                ('charms', models.IntegerField(default=0)),
                ('transfiguration', models.IntegerField(default=0)),
                ('potions', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('charm1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_charm', to='magicjourney.charm')),
                ('charm2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_charm', to='magicjourney.charm')),
                ('charm3', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_charm', to='magicjourney.charm')),
            ],
        ),
    ]
