# Generated by Django 3.1.3 on 2020-11-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicjourney', '0009_book_charm_cloak_wand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charm',
            name='effects_skill',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='charm',
            name='required_skill',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
