# Generated by Django 3.1.3 on 2020-11-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicjourney', '0010_auto_20201120_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cloak',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wand',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
