# Generated by Django 3.1.3 on 2020-11-20 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magicjourney', '0011_auto_20201120_1547'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cloak',
            new_name='Robe',
        ),
    ]
