# Generated by Django 3.1.3 on 2020-11-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicjourney', '0012_auto_20201120_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='robe',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='equipment_robe', to='magicjourney.Player'),
        ),
        migrations.AddField(
            model_name='wand',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='equipment_wand', to='magicjourney.Player'),
        ),
    ]
