# Generated by Django 3.1.3 on 2020-11-21 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magicjourney', '0014_book_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='wand',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='magicjourney.wand'),
        ),
    ]
