# Generated by Django 3.1.3 on 2020-11-21 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magicjourney', '0015_player_wand'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='book',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='magicjourney.book'),
        ),
        migrations.AddField(
            model_name='player',
            name='robe',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='magicjourney.robe'),
        ),
    ]
