# Generated by Django 3.1.3 on 2020-11-21 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magicjourney', '0016_auto_20201121_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='book',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='magicjourney.book', verbose_name='book'),
        ),
        migrations.AlterField(
            model_name='player',
            name='robe',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='magicjourney.robe', verbose_name='robe'),
        ),
        migrations.AlterField(
            model_name='player',
            name='wand',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='magicjourney.wand', verbose_name='wand'),
        ),
    ]
