# Generated by Django 3.1.3 on 2020-11-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicjourney', '0017_auto_20201121_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='equipment_book', to='magicjourney.Player', verbose_name='equipment_book'),
        ),
        migrations.AlterField(
            model_name='robe',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='equipment_robe', to='magicjourney.Player', verbose_name='equipment_robe'),
        ),
        migrations.AlterField(
            model_name='wand',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='equipment_wand', to='magicjourney.Player', verbose_name='equipment_wand'),
        ),
    ]
