# Generated by Django 3.1.3 on 2020-11-21 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magicjourney', '0019_wand_herbology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wand',
            name='herbology',
        ),
    ]
