# Generated by Django 3.1.3 on 2020-11-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicjourney', '0020_remove_wand_herbology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='equipment_book', to='magicjourney.Player'),
        ),
        migrations.AlterField(
            model_name='robe',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='equipment_robe', to='magicjourney.Player'),
        ),
        migrations.AlterField(
            model_name='wand',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='equipment_wand', to='magicjourney.Player'),
        ),
    ]
