# Generated by Django 3.1.3 on 2020-11-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicjourney', '0021_auto_20201121_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='wand',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
