# Generated by Django 3.1.3 on 2020-11-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicjourney', '0023_remove_wand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price_knuts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='robe',
            name='price_knuts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wand',
            name='price_knuts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='robe',
            name='price',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='wand',
            name='price',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
