# Generated by Django 3.1.3 on 2020-11-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicjourney', '0024_auto_20201121_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='charm',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='known_charms', to='magicjourney.Player'),
        ),
    ]
