# Generated by Django 3.1.3 on 2020-12-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicjourney', '0026_player_training_actions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('hp', models.IntegerField(default=0)),
                ('xp', models.IntegerField(default=0)),
                ('attack', models.IntegerField(default=0)),
                ('d_trans', models.IntegerField(default=0)),
                ('d_charms', models.IntegerField(default=0)),
            ],
        ),
    ]
