# Generated by Django 3.1.3 on 2020-12-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicjourney', '0027_creature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='story_status',
            field=models.CharField(default='start', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
